version: '3.8'

services:
  app:
    build: .
    container_name: rssify_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - ./logs:/app/logs
      - ./rssify.db:/app/rssify.db # Volume для SQLite БД
